Workaround for a MSVC 14.1 and 14.2 compiler bug * boost\include\boost/process/child.hpp(35): error C2600:     'boost::process::child::child': cannot define a compiler-generated     special member function (must be declared in the class first) * Introduced by 8541cae * See boostorg/process#113